name: Test Build
on: push

jobs:
  main:
    name: Build using PlatformIO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Install GD32V
        run: platformio platform install gd32v@1.1.1 --with-package framework-gd32vf103-sdk --with-package tool-gd32vflash
      - name: Remove bool definition killing C++ from SDK 
        run: sed -i -e 179d ~/.platformio/packages/framework-gd32vf103-sdk/GD32VF103_standard_peripheral/gd32vf103.h
      - name: Led
        run: platformio run -d Led
      - name: Freq
        run: platformio run -d Freq
      - name: Usart
        run: platformio run -d Usart
      - name: Lcd
        run: platformio run -d Lcd
      - name: Dma
        run: platformio run -d Dma
      - name: UsartIrq
        run: platformio run -d UsartIrq
      - name: PA8
        run: platformio run -d PA8
      - name: EspLink
        run: platformio run -d EspLink
      - name: EspLinkWeb
        run: platformio run -d EspLinkWeb
      - name: EspLinkSock
        run: platformio run -d EspLinkSock
      - name: I2c
        run: platformio run -d I2c
      - name: SpiDma
        run: platformio run -d SpiDma
      - name: GpioIrq
        run: platformio run -d GpioIrq
      - name: LcdFonts
        run: platformio run -d LcdFonts
      - name: Can
        run: platformio run -d Can
